version: "3.9"

services:
  node_db:
    container_name: node_db
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    env_file: ./.env
    ports:
      - $MSSQL_DOCKER_PORT:$MSSQL_LOCAL_PORT
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=$DB_PASSWORD
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: